version: '3.7'

services:
  terraform:
    image: hashicorp/terraform:1.2.0
    volumes:
      - .:/infra
#      - ${PWD}/id_rsa.pub:/root/.ssh/id_rsa.pub
    working_dir: /infra
    environment:
      - ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID}
      - ARM_TENANT_ID=${ARM_TENANT_ID}
      - ARM_CLIENT_ID=${ARM_CLIENT_ID}
      - ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET}
      - ARM_ACCESS_KEY=${ARM_ACCESS_KEY}
      