---
- name: "Install & configure Wordpress"
  hosts: _web_server
  become: yes
  pre_tasks:
    - name: "Install packages"
      apt: 
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - nginx
        - php-fpm
        - php-pgsql
        - git
  tasks: 
    - name: "Configuring wp cli"
      import_role:
        name: sbaerlocher.wp-cli

    - name: "Configuring wordpress"
      import_role:
        name: wordpress